import './globals.css'
import { DM_Sans } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'
import { Fanwood_Text } from 'next/font/google'
import type { AppProps } from "next/app"
import Link from "next/link"
import Header from "./common/header"
import customFont from "next/font/local"

export const body = Fanwood_Text({ weight: ["400"], style: ["normal"], subsets: ["latin"] })
export const bodyI = Fanwood_Text({ weight: ["400"], style: ["italic"], subsets: ["latin"] })
export const serif = DM_Serif_Display({ weight: ["400"], subsets: ["latin"] })
export const sans = DM_Sans({ weight: ["500"], subsets: ['latin'] })
export const humbleNostalgia = customFont({ src: "../public/fonts/HumbleNostalgia.otf" })
export const ntAdventure = customFont({ src: "../public/fonts/NTAdventure.otf"})
export const cospiog = customFont({ src: "../public/fonts/Cospiog.otf"})
export const cospiogI = customFont({ src: "../public/fonts/Cospiog-Italics.otf"})

//export const metadata = {
  //title: 'Create Next App',
  //description: 'Generated by create next app',
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={body.className}>
          <Header/>
          {children}
          </body>
      </html>
    </>
  )
}
