import './globals.css'
import { DM_Sans } from 'next/font/google'
import type { AppProps } from "next/app"
import Link from "next/link"
import Header from "./common/header"

const sans = DM_Sans({ weight: ["500"], subsets: ['latin'] })

//export const metadata = {
  //title: 'Create Next App',
  //description: 'Generated by create next app',
//}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className={sans.className}>
          <Header/>
          {children}
          </body>
      </html>
    </>
  )
}
